### ISSUE TITLE
Refresh the look and feel of the site

### ISSUE THREAD

**Issue by hasanhaja** [hasanhaja/hasanhaja-site#1]
https://www.cassie.codes/

This design is just amazing! The animation! The color palette and typography! Goregous!

I'd like to use this as inspiration when building out my site.

# Todo
## Add sections
- [ ] Mechanical keyboards
- [ ] Speedcubes
- [ ] Blog
- [ ] Picks

## SEO
- [ ] Add proper meta tags for SEO

## General
- [ ] Work on logo
- [ ] Work on style and theme
